version: "3.3"

services:
  cj_app:
    build:
      context: https://github.com/6rayWa1cher/course-journal-backend.git
    networks:
      - private_network
    depends_on:
      - cj_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cj_db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=${PROFILE:-prod}
      - JSON_REST_SECURITY_JWT_SECRET=${SECRET:-generate}
      - JSON_REST_SECURITY_CORS_ALLOWED_ORIGINS=${ORIGINS:-[]}
    ports:
      - '${PORT:-8080}:8080'

  cj_db:
    image: "postgres:14.1-alpine"
    networks:
      - private_network
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  private_network:

volumes:
  pgdata:
