# ===============================
# APPLICATION
# ===============================
app:
  version: '@project.version@ c:@git.commit.id.abbrev@_@git.build.time@ b:@maven.build.timestamp@'
  cors-allowed-origins: [ "http://localhost:8080", "http://localhost:3000" ]
# ===============================
# SPRING
# ===============================
spring:
  jmx:
    default-domain: com.a6raywa1cher.coursejournalbackend
    unique-names: true
# ===============================
# DB CONNECTION
# ===============================
spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.default_schema: public
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
# ===============================
# SPRING ACTUATOR
# ===============================
springdoc:
  show-actuator: true
#management.endpoints.web.exposure.include: "*"