# ===============================
# APPLICATION
# ===============================
app:
  version: '@project.version@ b:@maven.build.timestamp@'
# ===============================
# SPRING
# ===============================
spring:
  jmx:
    default-domain: com.a6raywa1cher.coursejournalbackend
    unique-names: true
server:
  forward-headers-strategy: framework
# ===============================
# DB CONNECTION
# ===============================
spring.datasource.url: jdbc:postgresql://localhost:5432/course-journal
spring.datasource.username: postgres
spring.datasource.password: postgres
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql: false
spring.jpa.hibernate.ddl-auto: update
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties:
  hibernate.default_schema: public
  hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  hibernate.temp.use_jdbc_metadata_defaults: false
# ===============================
# SPRINGDOC
# ===============================
springdoc:
  show-actuator: true
  swagger-ui:
    operations-sorter: alpha
    tagsSorter: alpha
# ===============================
# JSON-REST-SECURITY
# ===============================
#json-rest-security:
#  jwt:
#    secret: generate # use https://www.grc.com/passwords.htm
#    access-duration: P1D
