name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      CI: true
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: maven

      - name: Setup Maven
        run: mvn --batch-mode --update-snapshots compile

      - name: Run tests
        run: >
          mvn test
          -Dspring.jpa.show-sql=false
          -Dlogging.level.org.springframework.security=INFO

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}